### ISSUE TITLE
Apply newly created rules to all pending alerts

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#31] opened 2016-09-01 19:49 UTC
The first time I launched LittleFlocker I was greeted with a stream of alerts, as I'd expect. However, most of them were repeated alerts for the same permissions, even after I granted permission in the first alert. 

I granted permissions on those alerts as well, and when I went to view my rules I had multiple copies of the same rule:
![screen shot 2016-09-01 at 12 46 15 pm](https://cloud.githubusercontent.com/assets/4943/18181895/5cb0a1b6-7042-11e6-84a2-53ae06341f47.png)
(Note the rules for NotificationCenter in this screenshot)

I also tried creating a rule that allowed any process to read/write/create in my TemporaryItems folder and I still kept getting alerts for individual apps. I'm guessing those alerts were queued up from before I made that rule.

When permission is granted or denied that choice should be applied to any other alerts that are queued up.

**Comment by jzdziarski** [comment] 2016-09-01 19:54
Hello,

Each time you were alerted, did you select "Forever", or did you select a different time frame? Once or Until Quit can often result in repeated rule queries by design.

RE NotificationCenter, what i the path to the process you are providing?

**Comment by farktronix** [comment] 2016-09-01 20:02
I selected "Forever" in the alert every time.

The path to the NotificationCenter process that caused the alert is `/System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter`

It looks like the rules configuration window doesn't show how long a rule applies for. I'm guessing that window is only for "Forever" rules, or is it worth another issue to track showing the duration of the rule in that view?

**Comment by farktronix** [comment] 2016-09-01 20:16
This was with the 0.2.0 release, FWIW. I just noticed that 0.3.1 is available now so I'm upgrading.

**Comment by jzdziarski** [comment] 2016-09-01 21:23
Best thing would be to send me your rules file from /Users/Shared/Little Flocker and I can see the differences in the rules or add new defaults if necessary 

Pardon teh spellnig; sent form my iPhone

**Comment by jzdziarski** [comment] 2016-09-01 22:42
I'm not sure what you're doing, but it looks like you're running your OS and apps from /Volumes/Data; Little Flocker doesn't support non standard configurations like this, which explains why you got a lot of popups.

**Comment by jzdziarski** [comment] 2016-09-01 22:49
Closing this out as this is very clearly a non-standard, non-supported configuration.

**Closed by jzdziarski** 2016-09-01 22:49 UTC

**Comment by farktronix** [comment] 2016-09-01 22:52
My home directory is on a different partition from my OS install, but that is a config that's supported by macOS. 

You can change your home directory location in Settings->Users & Groups->ctrl+click on your user->Advanced Options... then select a different Home directory.

**Comment by jzdziarski** [comment] 2016-09-01 22:54
at the moment, LF expects your home directory to live in /Users; I think that's where most of your issues are coming from. So I'll create a new issue to add support for alternate home directories.

**Comment by farktronix** [comment] 2016-09-01 22:55
Sounds good- apologies for the storm of multiple bugs from that one issue :)

**Comment by jzdziarski** [comment] 2016-09-01 22:57
So is /Volumes/Data/.TemporaryItems some kind of remapped /tmp folder on your system?

**Comment by farktronix** [comment] 2016-09-01 22:58
That would make the most sense. Sorry I didn't grab the full path in my original report- I'm away from my laptop until later tonight but I'll grab it (and my config files) then.

**Comment by jzdziarski** [comment] 2016-09-01 23:28
It looks like there was something to this on further examination; I did find a case where at least one duplicate could be generated, and have fixed it for upcoming 0.3.2. IIWY I would examine the others to make sure they're all the same command; in some cases you may have "command" and "command via another command" all clumped together in the rules editor. You can view them all by clicking on them or by looking at the text file itself; this fix may at least account for one or two of those dupes. I suspect at least one dupe may be due to the way one was spawned, which the raw rules should reveal.
