### ISSUE TITLE
Cannot disable / re-enable more than once

### ISSUE THREAD

**Issue by dlo** [jzdziarski/littleflocker#42] opened 2016-09-06 17:46 UTC
After disabling Little Flocker and then re-enabling it, it appears you cannot disable it again.

**Comment by jzdziarski** [comment] 2016-09-06 18:10
Can't reproduce this one. But I suspect it might have something to do with your other issue related to malfunctioning. Going to close this out, so we can work on the other one and hopefully fix both.

**Comment by dlo** [comment] 2016-09-06 18:10
Sounds good. :)

**Closed by jzdziarski** 2016-09-06 18:10 UTC
