### ISSUE TITLE
Got five Welcome alerts after first install

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#30] opened 2016-09-01 19:45 UTC
I installed Little Flocker, rebooted, and I was greeted with five "Welcome to Little Flocker!" alerts
<img width="718" alt="screen shot 2016-09-01 at 12 34 55 pm" src="https://cloud.githubusercontent.com/assets/4943/18181804/eae17bc8-7041-11e6-8c5c-44aba41c6b45.png">

I grabbed a console log but I'd rather not attach it here. Please contact me directly and I'm happy to send it your way.

**Comment by jzdziarski** [comment] 2016-09-01 19:47
We want you to feel really welcome 👍 

(Thanks! Will look into it)

**Comment by farktronix** [comment] 2016-09-01 20:16
This was with the 0.2.0 release, FWIW. I just noticed that 0.3.1 is available now so I'm upgrading.

**Comment by jzdziarski** [comment] 2016-09-01 20:22
This should be fixed in 0.3.0 or later.

**Comment by farktronix** [comment] 2016-09-01 20:34
Sounds good. Is there a way I can reset all my state to try to reproduce this with 0.3.1?

**Comment by jzdziarski** [comment] 2016-09-01 20:36
delete your rules file in /Users/Shared/Little Flocker/
 
better yet, copy and paste it into an issue so I can look at it, then delete it and reboot.

**Comment by jzdziarski** [comment] 2016-09-01 21:46
Please reopen this issue if the problem is not resolved. It has been addressed in 0.3.0 so you should be good.

**Closed by jzdziarski** 2016-09-01 21:46 UTC
Labels: bug

**Comment by farktronix** [comment] 2016-09-02 16:14
Here are all of my rules:

`allow prefix "/Volumes/Data/pharkas/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword-osx-helper/" "/Applications/1Password.app/Contents/Library/LoginItems/2BUA8C4S2C.com.agilebits.onepassword-osx-helper.app/Contents/MacOS/2BUA8C4S2C.com.agilebits.onepassword-osx-helper" rwc
allow prefix "/Volumes/Data/.TemporaryItems" "any" rwc
allow prefix "/Volumes/Data/pharkas/Pictures/" "/System/Library/CoreServices/cloudphotosd.app/Contents/MacOS/cloudphotosd" rwc
allow suffix ".plist" "/System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper" rwc
allow suffix ".log" "/Applications/Utilities/Console.app/Contents/MacOS/Console" rwc
allow prefix "any" "/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder" rwc
allow prefix "/Users/Shared/.iStatMenus/" "/Library/Application Support/iStat Menus 5/iStat Menus Status.app/Contents/MacOS/iStat Menus Status" rwc
allow prefix "any" "/sbin/launchd" rwc
allow prefix "any" "/System/Library/CoreServices/launchservicesd" rwc
allow prefix "/Volumes/Data/.TemporaryItems/" "/Applications/Messages.app/Contents/MacOS/Messages" rwc
allow prefix "any" "/System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter" rwc
allow path "/Volumes/Data/pharkas/Applications/Flickr Uploadr.app/Contents/PkgInfo" "/System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter" rwc
allow suffix ".strings" "/System/Library/CoreServices/pbs" rwc
allow prefix "/Volumes/Data/pharkas/Library/Internet Plug-Ins/" "/Applications/Safari.app/Contents/MacOS/Safari" rwc
allow prefix "/Volumes/Data/pharkas/Library/Internet Plug-Ins/" "/Applications/Safari.app/Contents/MacOS/Safari" rwc
allow prefix "/Volumes/Data/.TemporaryItems/" "/System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeassetd" rwc
allow path "/Volumes/Data/pharkas/Library/Safari/Bookmarks.plist" "/usr/libexec/UserEventAgent" rwc
allow path "/private/var/db/lockdown/SystemConfiguration.plist" "/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd" rwc
allow prefix "/Volumes/Data/pharkas/.config/" "/usr/local/bin/fish via /usr/bin/login" rwc
allow path "/Volumes/Data/pharkas/Library/Application Support/iCloud/Accounts/" "/System/Library/PrivateFrameworks/AOSKit.framework/Versions/A/XPCServices/com.apple.iCloudHelper.xpc/Contents/MacOS/com.apple.iCloudHelper" rwc
allow prefix "/Volumes/Data/pharkas/Library/Application Support/1Password/Agent/1PasswordAgent.app/" "/Volumes/Data/pharkas/Library/Application Support/1Password/Agent/1PasswordAgent.app/Contents/MacOS/1PasswordAgent" rwc
allow prefix "/Volumes/Data/pharkas/Library/Application Support/Keybase/" "/Volumes/Data/pharkas/Applications/Keybase.app/Contents/SharedSupport/bin/updater" rwc
allow prefix "/Volumes/Data/pharkas/Applications/Dropbox.app/" "/Volumes/Data/pharkas/Applications/Dropbox.app/Contents/MacOS/Dropbox" rwc
allow prefix "/Volumes/Data/pharkas/Library/Application Support/iStat Menus/" "/Library/Application Support/iStat Menus 5/iStat Menus Status.app/Contents/MacOS/iStat Menus Status" rwc
allow suffix ".plist" "/usr/libexec/pkd" rwc
allow prefix "/Volumes/Data/pharkas/Applications/nugster.app/Contents/PlugIns/" "/Applications/Safari.app/Contents/MacOS/Safari" rwc
allow prefix "/Volumes/Data/pharkas/Library/Group Containers/2BUA8C4S2C.com.agilebits/" "/Applications/1Password.app/Contents/Library/LoginItems/2BUA8C4S2C.com.agilebits.onepassword-osx-helper.app/Contents/MacOS/2BUA8C4S2C.com.agilebits.onepassword-osx-helper" rwc
allow prefix "/Volumes/Data/pharkas/Library/Application Support/Spotify/" "/Volumes/Data/pharkas/Library/Application Support/Spotify/SpotifyWebHelper" rwc
allow prefix "any" "/usr/local/bin/fish via /usr/bin/login" rwc
allow prefix "/Volumes/Data/pharkas/Library/Application Support/1Password/" "/Volumes/Data/pharkas/Library/Application Support/1Password/Agent/1PasswordAgent.app/Contents/MacOS/1PasswordAgent" rwc
allow prefix "/Volumes/Data/pharkas/Applications/Dropbox.app/" "/Volumes/Data/pharkas/Applications/Dropbox.app/Contents/MacOS/Dropbox" rwc
allow prefix "/Volumes/Data/pharkas/Library/Mobile Documents/com~apple~TextInput/" "/System/Library/Frameworks/InputMethodKit.framework/Versions/A/XPCServices/com.apple.InputMethodKit.TextReplacementService.xpc/Contents/MacOS/com.apple.InputMethodKit.TextReplacementService" rwc
allow prefix "/private/var/db/lockdown/" "/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd" rwc
`

**Comment by jzdziarski** [comment] 2016-09-02 18:08
thanks, i took the relevant portions of your rules list and added a few of them to the default rules
